### ISSUE TITLE
Support  "etcd --listen-metrics-urls"

### ISSUE THREAD

**Issue by granular-ryanbonham** [kopeio/etcd-manager#139]
Enable a separate port for metrics and allow access from node SG to simplify pulling etcd metrics in a secure way. Requires Upgrade to etc 3.3.0+ as well.

Tag for K8s 1.1.14 where etcd has been defaulted to 3.3.10

**Comment by priegger** [comment]
Is this fixed in #232?

**Comment by olemarkus** [comment]
Looks like this one is fixed.

**Comment by justinsb** [comment]
This one should now be fixed.  We had a typo in the flag name, but that'll be fixed and merged into the next release.

/close
