### ISSUE TITLE
Provide etcd-manager-ctl binaries

### ISSUE THREAD

**Issue by marcindulak** [kopeio/etcd-manager#201]
The documentation at https://github.com/kopeio/etcd-manager mentions `etcd-manager-ctl` as the tool for the management of the etcd backups/restores. Would it be possible to include that tool in https://hub.docker.com/r/kopeio/etcd-manager?

Moreover it would be useful to have described also a more realistic scenario of the usage of `etcd-manager-ctl` for backups/restores on an aws/other system managed by kops.

**Comment by pracucci** [comment]
I'm not sure embedding `etcd-manager-ctl` in the Docker image is the right approach. The ctl has been designed to be used on the operator workstation, in order to issue commands on the `etcd-manager` cluster (commands are json files uploaded to the remote storage).

Wouldn't more appropriate providing a compiled binary for osx and linux for each release?

/cc @justinsb

**Comment by dbarranco** [comment]
yes, please.
It would be very useful to have a list of compiled binaries to download, as we can do with the Kops tool.

Also, some documentation for the  etcd-manager-ctl tool would be convenient, as it is not very clear which are the requirements the tool need to run, i.e. TLS certs of the etcd cluster.

Thanks for all the work!

**Comment by vijay-veeranki-moj** [comment]
I can't find any Instructions about building this binary, I am new to bazel, can you please help me to get this working please @pracucci.

**Comment by pracucci** [comment]
@vijay-veeranki-moj In the past I've successfully built `etcd-manager-ctl` using this Dockerfile:

```
FROM ubuntu:16.04

ARG VERSION=3.0.20190516

# Install dependencies
RUN apt-get update && \
    apt-get install --yes golang-1.10-go git wget awscli

# Install bazel 0.26.1, which is a known working version
RUN wget http://storage.googleapis.com/bazel-apt/pool/jdk1.8/b/bazel/bazel_0.26.1_amd64.deb -O /tmp/bazel_0.26.1_amd64.deb && \
    apt-get install --yes /tmp/bazel_0.26.1_amd64.deb

# Downloads etcd-manager sources
RUN wget https://github.com/kopeio/etcd-manager/archive/${VERSION}.tar.gz -O /tmp/sources.tar.gz && \
    cd /tmp && \
    tar -zxvf sources.tar.gz

# Compile
ARG CMD_NAME=etcd-manager-ctl
ENV PATH=/usr/lib/go-1.10/bin/:${PATH}

RUN cd /tmp/etcd-manager-${VERSION} && \
    bazel build //cmd/${CMD_NAME} && \
    mkdir /tmp/etcd-manager-artifacts && \
    cp /tmp/etcd-manager-${VERSION}/bazel-genfiles/cmd/${CMD_NAME}/linux_amd64_stripped/${CMD_NAME} /tmp/etcd-manager-artifacts/${CMD_NAME}-linux-amd64-${VERSION}
```

**Comment by vijay-veeranki-moj** [comment]
Thanks @pracucci

I was using `https://github.com/kopeio/etcd-manager/releases`
