### ISSUE TITLE
Default backup retention period

### ISSUE THREAD

**Issue by qw1mb0** [kopeio/etcd-manager#225]
Good day.

We use etcd-manager with kops to manage etcd. By default, etcd-managetr sets up backups to the bake, every 15 minutes. But I could not find out what default retention (https://github.com/kopeio/etcd-manager/blob/master/pkg/backupcontroller/cleanup.go) is worth it and how can it be configured?

**Comment by luarx** [comment]
Yeah, I want to know also what is the retention period and if I could change it

**Comment by ivnilv** [comment]
+1

**Comment by denisgranha** [comment]
+2
