### ISSUE TITLE
etcd 3.3.15

### ISSUE THREAD

**Issue by den-is** [kopeio/etcd-manager#249]
Hopefully this beautiful piuece of software will be update to latest etcd to enable latest secutiry fixes

https://groups.google.com/forum/#!msg/golang-announce/65QixT3tcmg/DrFiG6vvCwAJ

https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3315-2019-08-19

:)

**Comment by den-is** [comment]
https://github.com/kubernetes/kubernetes/pull/82199

**Comment by den-is** [comment]
3.3.17 in 1.17
https://github.com/kubernetes/kubernetes/pull/83804

**Comment by mmerrill3** [comment]
3.4.3 now for k8s 1.17 https://github.com/kubernetes/kubernetes/pull/84329

**Comment by mmerrill3** [comment]
I think this can be closed?

https://github.com/kubernetes/kubernetes/blob/b8b4186a14045ab66b150b5a92276d02b8a73a3e/cmd/kubeadm/app/constants/constants.go#L425

3.3.15 is not the default anymore for k8s 1.16, its 3.3.17.

**Comment by den-is** [comment]
yea sure
