### ISSUE TITLE
Update module version of kops

### ISSUE THREAD

**Issue by bittopaz** [kopeio/etcd-manager#268]
Currently etcd-manager depends on an very old kops version.

I'm currently working on make etct-manager support Alicloud, in this case, I need to update the vfs module in kops.

But I don't know what is the best way to upgrade kops dependency in etcd-manager.

Can you please take a look at this? @justinsb  

This is blocking #269.

Thanks!

**Comment by justinsb** [comment]
You're right, and it proved less easy to update than it should have been because of the way our staging repos end up with versions v0.0.0 ...

Working on an update in https://github.com/kopeio/etcd-manager/pull/278
