### ISSUE TITLE
How to get metrics from etcd after migration to etcdmanager?

### ISSUE THREAD

**Issue by michalschott** [kopeio/etcd-manager#286]
Hi,

I'm using datadog for monitoring solution, but I feel like this is more generic question. Previously (before etcdmanager was introduced) port 4001 and 4002 were accessible, and if I recall correctly these are not exposed on nodes anymore.

Previously, our datadog check was configured like this:
```
---
init_config:
instances:
  - url: http://etcd-a.internal.CLUSTER_NAME:4001
```

What's the correct url to use now?

**Comment by carpenterbees** [comment]
After upgrade to etcd v3, metrics endpoint is available only on https port which requires auth with TLS certificate.
Your monitoring client has to provide certificate to be able to read from etcd nodes. 

Another solution is to configure custom url:

**Comment by carpenterbees** [comment]
After upgrade to etcd v3, metrics endpoint is available only on https port which requires auth with TLS certificate.
Your monitoring client has to provide certificate to be able to read from etcd nodes. 

Another solution is to configure custom url:
[Support listen-metrics-url|https://github.com/kopeio/etcd-manager/pull/232/commits/02310647f0be19a353bb09a16893a153360751d8]

**Comment by michalschott** [comment]
Hi @carpenterbees, thanks for pointing me to proper PR. I was able to expose the endpoint and scratch the metrics again. Raised a PR in kops to see if we can enable this by default.

**Comment by themoah** [comment]
@michalschott can you, please, share how you've exposed metrics ? I'm having same problem with datadog.
thanks !

**Comment by michalschott** [comment]
@themoah https://github.com/kubernetes/kops/pull/8162

**Comment by themoah** [comment]
@michalschott can you share the configuration of the pods ? Appreciate the help
