### ISSUE TITLE
Restore Results In  0.0.0.0:8081: bind: address already in use if ETCD_LISTEN_METRICS_URLS is used

### ISSUE THREAD

**Issue by granular-ryanbonham** [kopeio/etcd-manager#368]
Etcdmanager can not do a restore if ETCD_LISTEN_METRICS_URLS is in use.  It tries to apply those settings to etcd used by the restore process resulting in etcdmain: listen tcp 0.0.0.0:8081: bind: address already in use.

Current workound is to disable ETCD_LISTEN_METRICS_URLS then do the restore.

**Comment by granular-ryanbonham** [comment]
https://github.com/kopeio/etcd-manager/pull/369

**Comment by rifelpet** [comment]
looks like this issue can be closed
