### ISSUE TITLE
Bazel build fails

### ISSUE THREAD

**Issue by tamalsaha** [kopeio/etcd-manager#45]
Hi Justin,
I am trying to build etcd-manager and I am getting the following error:

```
 $ bazel build //cmd/etcd-manager //cmd/etcd-manager-ctl
ERROR: /home/tamal/go/src/kope.io/etcd-manager/cmd/etcd-manager-ctl/BUILD.bazel:3:1: no such package 'vendor/github.com/golang/glog': BUILD file not found on package path and referenced by '//cmd/etcd-manager-ctl:go_default_library'
ERROR: Analysis of target '//cmd/etcd-manager-ctl:etcd-manager-ctl' failed; build aborted: no such package 'vendor/github.com/golang/glog': BUILD file not found on package path
INFO: Elapsed time: 0.311s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: @io_bazel_rules_go//go/private
```

This is my first time using bazel. I installed bazel on a Ubuntu 16.04 machine following instructions here: https://docs.bazel.build/versions/master/install-ubuntu.html

Any idea how to fix this error ?

**Comment by justinsb** [comment]
Hmm.. .that's odd.  We do have travis testing this also, so I just added testing of multiple versions ( #46 ) - hopefully that'll show the error.  What is your `bazel version`?

**Comment by justinsb** [comment]
Should work with bazel 0.8.1 and 0.9.0 at least - those are the tested configurations!

**Comment by tamalsaha** [comment]
I was able to build it after cleanly reinstalling bazel 0.9.0. Thanks Justin!
